# Removed version: '3.8' as it's obsolete for V2 and caused warnings

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama_server_managed # Changed name slightly to avoid conflicts if old one exists
    ports:
      - "11434:11434" # Expose Ollama port to host
    volumes:
      - ollama_data:/root/.ollama # Persist downloaded models
    # --- Uncomment the following lines if you have an NVIDIA GPU ---
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1 # Or 'all'
    #           capabilities: [gpu]
    # --- ---
    # Healthcheck removed as it was problematic; we'll rely on API calls succeeding
    restart: unless-stopped

volumes:
  ollama_data: # Define the named volume for Ollama models
