// Favicon switching: one SVG per Radix accent color (light + dark tile),
// generated by scripts/generate-favicons.mjs into public/favicons/.

import { isRadixAccentColor } from '../store/ui/accentColorAtom';

export const DEFAULT_FAVICON_ACCENT = 'indigo';

export function faviconHref(
  accent: unknown,
  appearance: 'light' | 'dark'
): string {
  const name =
    typeof accent === 'string' && isRadixAccentColor(accent)
      ? accent
      : DEFAULT_FAVICON_ACCENT;
  return `/favicons/${name}${appearance === 'dark' ? '-dark' : ''}.svg`;
}

export function applyFavicon(href: string): void {
  if (typeof document === 'undefined') return;
  let link = document.querySelector<HTMLLinkElement>('link#favicon-svg');
  if (!link) {
    link = document.createElement('link');
    link.id = 'favicon-svg';
    link.rel = 'icon';
    link.type = 'image/svg+xml';
    document.head.appendChild(link);
  }
  link.setAttribute('href', href);
}
